#ifndef GATT_CLIENT_IDENTIFIERS_H
#define GATT_CLIENT_IDENTIFIERS_H

#include "gatt_client.h"

/* List of gatt client identifiers (generated by the gatt client create macros in gatt_client.h) */
extern const client_id_t gatt_ams_client_id;
extern const client_id_t gatt_ancs_client_id;

#endif
